### ISSUE TITLE
Missing Icons Telegram and QBittorrent

### ISSUE THREAD

**Issue by Faust30000** [lestcape/Systray-Indicator#5]
After installing this applet, the program icons Telegram and QBittorrent disappeared from the panel. Instead, they are empty space. I deleted your applet, but everything remained as before. How can I fix this? !!!
Linux Mint 18.1 Cinnamon.

**Comment by lestcape** [comment]
Hi, @Faust30000 this is just a repository, where i test this feature, to be merged inside the cinnamon desktop. It was merged and you don' t required this applet at all, this only conflicted with the cinnamon code. So, not install it. In the settings of cinnamon, you will see in the general setting an option to enable the indicator support.

I don' t work any more for cinnamon, and i don' t use it, as clement fork all third-party extensions, and i disagree with his model. Where third-party developer will need to work for Mint distro, if really they want to developer something for cinnamon. So, non of my applets or desklets have support for cinnamon anymore. Clement say this if for users, but will not be for users if his new rules disturbed the real developer of an extension. So, in my personal case it's the opposite.
